mysql:
    image: mysql
    ports:
        - "8806:3306"
    volumes:
        - /Users/lujin/data/var/mysql/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: test
        MYSQL_USER: lujin
        MYSQL_PASSWORD: 123456
